# Generated by Django 5.1.1 on 2025-01-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_event_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='available',
        ),
    ]
