# Generated by Django 5.1.1 on 2025-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_service_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='hotel.service'),
        ),
    ]
